# Generated by Django 3.1.1 on 2020-09-20 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_paslon'),
    ]

    operations = [
        migrations.CreateModel(
            name='votemasuk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu', models.DateTimeField()),
                ('pilihan', models.TextField()),
            ],
        ),
    ]
