# Generated by Django 3.1.1 on 2020-09-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_votemasuk'),
    ]

    operations = [
        migrations.AddField(
            model_name='votemasuk',
            name='nama',
            field=models.TextField(default='bjir'),
            preserve_default=False,
        ),
    ]
